apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/katib/manifests/v1beta1/installs/katib-with-kubeflow?ref=release-0.11

images:
- name: docker.io/kubeflowkatib/katib-controller
  newName: docker.io/kubeflowkatib/katib-controller
  newTag: v0.11.0
  digest: sha256:c5e74b2309cef034db4fdcc4d2789004b687d6aa862e1b6d9ab3921ffacd707a
- name: docker.io/kubeflowkatib/katib-db-manager
  newName: docker.io/kubeflowkatib/katib-db-manager
  newTag: v0.11.0
  digest: sha256:aca286cfc6f357d4ef6d3ed69c17a471fd1a320a0f09f8b0fe770c9d5607f847
- name: docker.io/kubeflowkatib/katib-ui
  newName: docker.io/kubeflowkatib/katib-new-ui
  newTag: v0.11.0
  digest: sha256:d8d738394379f794bf49e687a6cb8478ec08ec3a553e312d2df1ffdef08d6b97
- name: mysql
  newName: mysql
  newTag: "8"
  digest: sha256:355617769102e9d2ebb7d5879263a12d230badb7271c91748b2c7b0ac6971083
