apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
- github.com/kubeflow/manifests/common/dex/overlays/istio

patchesStrategicMerge:
- configmap-patch.yaml

images:
- name: quay.io/dexidp/dex
  newName: ghcr.io/dexidp/dex
  newTag: v2.28.1
  # digest: sha256:5e88f2205de172b60fd7af23ac92f34321688a83de9f7de7c9a6f394f6950877
