apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/admission-webhook/manifests/overlays/cert-manager?ref=8901e3af3b83f599b89562162cdb2854f57082d3 # tag=v1.3.0-rc.1

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook
  newName: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook
  newTag: v1.3.0-rc.0
