apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
## Common
# - argocd-applications/metallb.yaml
# - argocd-applications/rook-ceph.yaml
# - argocd-applications/nginx.yaml
# - argocd-applications/nvidia-gpu-operator.yaml
- argocd-applications/istio-operator.yaml
- argocd-applications/istio.yaml    
- argocd-applications/istio-resources.yaml
# - argocd-applications/knative.yaml

# Pick *one* of the following applications
- argocd-applications/argocd.yaml
# - argocd-applications/argocd-private-repo.yaml

# Pick *one* of the following applications 
- argocd-applications/cert-manager-self-signing.yaml
# - argocd-applications/cert-manager-dns-01.yaml

# Pick *one* of the following
- argocd-applications/certificates.yaml
# - argocd-applications/certificates-imported.yaml

# Pick *one* of the following applications:  
# - argocd-applications/oidc-auth-on-cluster-dex.yaml
- argocd-applications/oidc-auth-on-cluster-keycloak.yaml
# - argocd-applications/oidc-auth-external.yaml

## Kubeflow  
- argocd-applications/central-dashboard.yaml
- argocd-applications/profile-controller_access-management.yaml
- argocd-applications/kubeflow-namespace.yaml
- argocd-applications/kubeflow-roles.yaml
- argocd-applications/pipelines.yaml
- argocd-applications/katib.yaml
- argocd-applications/kfserving.yaml
- argocd-applications/pod-defaults.yaml
- argocd-applications/jupyter-web-app.yaml
- argocd-applications/notebook-controller.yaml
- argocd-applications/tensorboard-controller.yaml
- argocd-applications/tensorboards-web-app.yaml
- argocd-applications/volumes-web-app.yaml
- argocd-applications/tensorflow-operator.yaml
- argocd-applications/pytorch-operator.yaml
- argocd-applications/mpi-operator.yaml
- argocd-applications/mxnet-operator.yaml
- argocd-applications/xgboost-operator.yaml

## System
# - argocd-applications/external-dns.yaml
# - argocd-applications/cloudflare-secrets.yaml
- argocd-applications/sealed-secrets.yaml

## Monitoring and logging
# - argocd-applications/monitoring-resources.yaml
# - argocd-applications/kube-prometheus-stack.yaml
# - argocd-applications/loki-stack.yaml
# - argocd-applications/kiali.yaml
# - argocd-applications/kubecost.yaml

## Contrib
# - argocd-applications/mlflow.yaml
# - argocd-applications/experimental-pvcviewer-controller.yaml
# - argocd-applications/experimental-volumes-web-app.yaml
