apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubernetes/ingress-nginx/deploy/static/provider/cloud?ref=controller-v0.45.0
- gitlab-tcp-configmap.yaml

patchesStrategicMerge:
- deployment_patch.yaml
- gitlab-service-patch.yaml
