apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/jetstack/cert-manager/releases/download/v1.3.0/cert-manager.yaml
- kubeflow-self-signed-issuer.yaml
# If you would like to setup a letsencrypt cluster issuer,
# edit the `letsencrypt-cluster-issuer.yaml` with your details
# see: https://cert-manager.io/docs/configuration/acme/#configuration
# and uncomment the following line
# - letsencrypt-cluster-issuer.yaml

images:
- name: quay.io/jetstack/cert-manager-controller
  newName: quay.io/jetstack/cert-manager-controller
  newTag: v1.3.1
  digest: sha256:c5e61db0facc5fa63b310384f968e294414b976677b550ef5306cc410add2abc
- name: quay.io/jetstack/cert-manager-cainjector
  newName: quay.io/jetstack/cert-manager-cainjector
  newTag: v1.3.0
  digest: sha256:cda85f01dc9beec5b44087065ae6e71bfedddeaf0b0a6a3e67951284debfe342
- name: quay.io/jetstack/cert-manager-webhook
  newName: quay.io/jetstack/cert-manager-webhook
  newTag: v1.3.0
  digest: sha256:414aba29f1428d0e6ab061dc0fac78f7db86ebedda5f45e2b28155f3d6a322fd
