apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/tf-operator/manifests/overlays/kubeflow?ref=6f1e96c4b3e7b63860780b6f572ec229e58ca146 # tag=v1.1.1

images:
- name: public.ecr.aws/j1r0q0g6/training/tf-operator
  newName: public.ecr.aws/j1r0q0g6/training/tf-operator
  newTag: cd2fc1ff397b1f349f68524f4abd5013a32e3033
  # digest: sha256:b10739e751783fc0878505a4b2078c61a3d2a4471a7762f01e320d2f2ef162bd
